version: "3.7"

services:

#----------------------------------------------------------------------------------
    app_flask:
        container_name: app_flask
        build:
            context: .
            dockerfile: flaskblog/DockerFlask
        command: bash -c "gunicorn --bind 0.0.0.0:5000 flaskblog.run:app"
        networks:
            my_network:
                ipv4_address: 172.20.1.50
        volumes:
            - ./flaskblog/log_app:/flaskblog/log
        env_file:
            - ./flaskblog/dock_flask.env
        restart: always
        depends_on:
            - nginx

#----------------------------------------------------------------------------------
    pgadmin:
        container_name: pgadmin_flask
        image: dpage/pgadmin4
        networks:
            my_network:
                ipv4_address: 172.20.1.3
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
            - PGADMIN_LISTEN_ADDRESS=0.0.0.0
            - PGADMIN_LISTEN_PORT=5123
        restart: always
        depends_on:
            - db

#----------------------------------------------------------------------------------
    db:
        container_name: postgresql_db_flask
        image: postgres:16
        restart: always
        networks:
            my_network:
                ipv4_address: 172.20.1.2
        ports:
            - "9032:5432"
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - ./pg_db:/var/lib/postgresql/data/

#----------------------------------------------------------------------------------
    nginx:
        container_name: nginx_flask
        build:
            context: .
            dockerfile: ./nginx/Docker-nginx
        networks:
            my_network:
                ipv4_address: 172.20.1.1
        ports:
            - "1443:443"
        restart: always

#----------------------------------------------------------------------------------
networks:
    my_network:
        name: app_net_new
        external: true
